[project]
name = "differential-analysis"
version = "0.1.0"
description = "Utility scripts to perform differential analysis on peaks and annotate the significant ones"
channels = ["conda-forge", "bioconda", "default"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.18"

[tasks]

[dependencies]
pandas = ">=2.2.2,<2.3"
python = "3.12.*"
r-base = ">=4.3.3,<4.4"
r-biocmanager = ">=1.30.23,<1.31"
"r-data.table" = ">=1.15.4,<1.16"
r-argparser = ">=0.7.2,<0.8"
homer = ">=4.11,<5"
bioconductor-diffbind = ">=3.12.0,<3.13"
numpy = ">=2.0.1,<2.1"
